/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"



/* ---------------------------------------- */


/*
 * FUNCTION safe-/
 */
extern_c real C_safe_Over(flt L1_num,flt L1_den)
{
TRACE_PUSH("C_safe_Over");
{
real L_Tmp0;
 if ((L1_den==0)) { 
L_Tmp0 = 0;
 } else { 
L_Tmp0 = (L1_num/(flt)L1_den);
 } 
TRACE_POP("C_safe_Over");
return L_Tmp0;
}
}

/*
 * FUNCTION round
 */
extern_c int C_round(flt L1_x)
{
TRACE_PUSH("C_round");
{
int L_Tmp0;
L_Tmp0 = (L1_x+0.5);
L_Tmp0 = ((int)floor((double)L_Tmp0));
TRACE_POP("C_round");
return L_Tmp0;
}
}

/*
 * FUNCTION round-using
 */
extern_c flt C_round_using(flt L1_x,flt L1_d)
{
TRACE_PUSH("C_round_using");
{
flt L_Tmp0;
int L_Tmp1;
L_Tmp1 = (int) C_round((L1_x*L1_d));
L_Tmp0 = (L_Tmp1/(flt)L1_d);
TRACE_POP("C_round_using");
return L_Tmp0;
}
}

/*
 * FUNCTION round-to
 */
extern_c flt C_round_to(flt L1_x,flt L1_tol)
{
TRACE_PUSH("C_round_to");
{
flt L_Tmp0;
int L_Tmp1;
L_Tmp1 = (int) C_round((L1_x/(flt)L1_tol));
L_Tmp0 = (L_Tmp1*L1_tol);
TRACE_POP("C_round_to");
return L_Tmp0;
}
}

/*
 * FUNCTION match-sign
 */
extern_c real C_match_sign(flt L1_a,flt L1_b)
{
TRACE_PUSH("C_match_sign");
{
real L_Tmp0;
 if ((L1_b>=0)) { 
L_Tmp0 = Fabs(L1_a);
 } else { 
L_Tmp0 = (-Fabs(L1_a));
 } 
TRACE_POP("C_match_sign");
return L_Tmp0;
}
}

/*
 * FUNCTION lu-decomposition
 */
extern_c flt C_lu_decomposition(struct idx* L1_a,int L1_n,struct idx* L1_indx)
{
TRACE_PUSH("C_lu_decomposition");
{
flt L_Tmp0;
int L3_1_j;
{
flt L2_2_d;
flt L2_3_TimestinyTimes;
int L2_4_i;
int L2_5_imax;
int L2_6_j;
int L2_7_k;
flt L2_8_big;
flt L2_9_dum;
flt L2_10_sum;
flt L2_11_temp;
Midx_declare(L2_12_0_matrix, 1);
Msrg_declare(L2_13_0_srg);
struct idx* L2_14_vv;
Midx_init(L2_12_0_matrix, 1);
Msrg_init(L2_13_0_srg, ST_F);
L2_2_d = 1;
L2_3_TimestinyTimes = 1e-20;
L2_4_i = 0;
L2_5_imax = 0;
L2_6_j = 0;
L2_7_k = 0;
L2_8_big = 0;
L2_9_dum = 0;
L2_10_sum = 0;
L2_11_temp = 0;
(L2_12_0_matrix)->srg = L2_13_0_srg;
Midx_init_dim1(L2_12_0_matrix, ((L1_n)+1));
RTERR_DIM(L2_12_0_matrix->dim[0]<=0);
Midx_maclear(L2_12_0_matrix, flt);
L2_14_vv = L2_12_0_matrix;
{
real L3_15_i;
L3_15_i = 1;
for(;
((1>0)?(L3_15_i<=L1_n):(L3_15_i>=L1_n));
(L3_15_i)+=1 ) {
L2_8_big = 0;
{
real L4_16_j;
L4_16_j = 1;
for(;
((1>0)?(L4_16_j<=L1_n):(L4_16_j>=L1_n));
(L4_16_j)+=1 ) {
RTERR_BOUND(L3_15_i<0 || L3_15_i>=(L1_a)->dim[0]);
RTERR_BOUND(L4_16_j<0 || L4_16_j>=(L1_a)->dim[1]);
L2_11_temp = Fabs(IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L3_15_i)+(L1_a)->mod[1]*((int)L4_16_j)]);
 if ((L2_11_temp>L2_8_big)) { 
L2_8_big = L2_11_temp;
 } 
}
}
 if ((L2_8_big==0)) { 
run_time_error("Singular matrix in function LU-decomposition");
 } 
RTERR_BOUND(L3_15_i<0 || L3_15_i>=(L2_14_vv)->dim[0]);
IDX_PTR(L2_14_vv,flt)[(L2_14_vv)->mod[0]*((int)L3_15_i)] = (1/(flt)L2_8_big);
}
}
{
L3_1_j = 1;
for(;
((1>0)?(L3_1_j<=L1_n):(L3_1_j>=L1_n));
(L3_1_j)+=1 ) {
{
real L4_17_i;
int L_Tmp18;
L_Tmp18 = ((L3_1_j)-1);
L4_17_i = 1;
for(;
((1>0)?(L4_17_i<=L_Tmp18):(L4_17_i>=L_Tmp18));
(L4_17_i)+=1 ) {
RTERR_BOUND(L4_17_i<0 || L4_17_i>=(L1_a)->dim[0]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[1]);
L2_10_sum = IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L4_17_i)+(L1_a)->mod[1]*((int)L3_1_j)];
{
real L5_19_k;
real L_Tmp20;
L_Tmp20 = ((L4_17_i)-1);
L5_19_k = 1;
for(;
((1>0)?(L5_19_k<=L_Tmp20):(L5_19_k>=L_Tmp20));
(L5_19_k)+=1 ) {
RTERR_BOUND(L4_17_i<0 || L4_17_i>=(L1_a)->dim[0]);
RTERR_BOUND(L5_19_k<0 || L5_19_k>=(L1_a)->dim[1]);
RTERR_BOUND(L5_19_k<0 || L5_19_k>=(L1_a)->dim[0]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[1]);
L2_10_sum = (L2_10_sum-(IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L4_17_i)+(L1_a)->mod[1]*((int)L5_19_k)]*IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L5_19_k)+(L1_a)->mod[1]*((int)L3_1_j)]));
}
}
RTERR_BOUND(L4_17_i<0 || L4_17_i>=(L1_a)->dim[0]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[1]);
IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L4_17_i)+(L1_a)->mod[1]*((int)L3_1_j)] = L2_10_sum;
}
}
L2_8_big = 0;
{
real L4_21_i;
L4_21_i = L3_1_j;
for(;
((1>0)?(L4_21_i<=L1_n):(L4_21_i>=L1_n));
(L4_21_i)+=1 ) {
RTERR_BOUND(L4_21_i<0 || L4_21_i>=(L1_a)->dim[0]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[1]);
L2_10_sum = IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L4_21_i)+(L1_a)->mod[1]*((int)L3_1_j)];
{
real L5_22_k;
int L_Tmp23;
L_Tmp23 = ((L3_1_j)-1);
L5_22_k = 1;
for(;
((1>0)?(L5_22_k<=L_Tmp23):(L5_22_k>=L_Tmp23));
(L5_22_k)+=1 ) {
RTERR_BOUND(L4_21_i<0 || L4_21_i>=(L1_a)->dim[0]);
RTERR_BOUND(L5_22_k<0 || L5_22_k>=(L1_a)->dim[1]);
RTERR_BOUND(L5_22_k<0 || L5_22_k>=(L1_a)->dim[0]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[1]);
L2_10_sum = (L2_10_sum-(IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L4_21_i)+(L1_a)->mod[1]*((int)L5_22_k)]*IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L5_22_k)+(L1_a)->mod[1]*((int)L3_1_j)]));
}
}
RTERR_BOUND(L4_21_i<0 || L4_21_i>=(L1_a)->dim[0]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[1]);
IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L4_21_i)+(L1_a)->mod[1]*((int)L3_1_j)] = L2_10_sum;
RTERR_BOUND(L4_21_i<0 || L4_21_i>=(L2_14_vv)->dim[0]);
L2_9_dum = (IDX_PTR(L2_14_vv,flt)[(L2_14_vv)->mod[0]*((int)L4_21_i)]*Fabs(L2_10_sum));
 if ((L2_9_dum>=L2_8_big)) { 
L2_8_big = L2_9_dum;
L2_5_imax = L4_21_i;
 } 
}
}
 if ((L3_1_j!=L2_5_imax)) { 
{
real L4_24_k;
L4_24_k = 1;
for(;
((1>0)?(L4_24_k<=L1_n):(L4_24_k>=L1_n));
(L4_24_k)+=1 ) {
RTERR_BOUND(L2_5_imax<0 || L2_5_imax>=(L1_a)->dim[0]);
RTERR_BOUND(L4_24_k<0 || L4_24_k>=(L1_a)->dim[1]);
L2_9_dum = IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L2_5_imax)+(L1_a)->mod[1]*((int)L4_24_k)];
RTERR_BOUND(L2_5_imax<0 || L2_5_imax>=(L1_a)->dim[0]);
RTERR_BOUND(L4_24_k<0 || L4_24_k>=(L1_a)->dim[1]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[0]);
RTERR_BOUND(L4_24_k<0 || L4_24_k>=(L1_a)->dim[1]);
IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L2_5_imax)+(L1_a)->mod[1]*((int)L4_24_k)] = IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L3_1_j)+(L1_a)->mod[1]*((int)L4_24_k)];
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[0]);
RTERR_BOUND(L4_24_k<0 || L4_24_k>=(L1_a)->dim[1]);
IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L3_1_j)+(L1_a)->mod[1]*((int)L4_24_k)] = L2_9_dum;
}
}
L2_2_d = (L2_2_d*-1);
RTERR_BOUND(L2_5_imax<0 || L2_5_imax>=(L2_14_vv)->dim[0]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L2_14_vv)->dim[0]);
IDX_PTR(L2_14_vv,flt)[(L2_14_vv)->mod[0]*((int)L2_5_imax)] = IDX_PTR(L2_14_vv,flt)[(L2_14_vv)->mod[0]*((int)L3_1_j)];
 } 
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_indx)->dim[0]);
IDX_PTR(L1_indx,flt)[(L1_indx)->mod[0]*((int)L3_1_j)] = L2_5_imax;
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[0]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[1]);
 if ((IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L3_1_j)+(L1_a)->mod[1]*((int)L3_1_j)]==0)) { 
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[0]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[1]);
IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L3_1_j)+(L1_a)->mod[1]*((int)L3_1_j)] = L2_3_TimestinyTimes;
 } 
 if ((L3_1_j!=L1_n)) { 
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[0]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[1]);
L2_9_dum = (1/(flt)IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L3_1_j)+(L1_a)->mod[1]*((int)L3_1_j)]);
{
real L4_25_i;
L4_25_i = ((L3_1_j)+1);
for(;
((1>0)?(L4_25_i<=L1_n):(L4_25_i>=L1_n));
(L4_25_i)+=1 ) {
RTERR_BOUND(L4_25_i<0 || L4_25_i>=(L1_a)->dim[0]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[1]);
RTERR_BOUND(L4_25_i<0 || L4_25_i>=(L1_a)->dim[0]);
RTERR_BOUND(L3_1_j<0 || L3_1_j>=(L1_a)->dim[1]);
IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L4_25_i)+(L1_a)->mod[1]*((int)L3_1_j)] = (IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L4_25_i)+(L1_a)->mod[1]*((int)L3_1_j)]*L2_9_dum);
}
}
 } 
}
}
L_Tmp0 = L2_2_d;
Msrg_free(L2_13_0_srg);
}
TRACE_POP("C_lu_decomposition");
return L_Tmp0;
}
}

/*
 * FUNCTION lu-back-substitution
 */
extern_c struct idx* C_lu_back_substitution(struct idx* L1_a,int L1_n,struct idx* L1_indx,struct idx* L1_b)
{
TRACE_PUSH("C_lu_back_substitution");
{
struct idx* L_Tmp0;
int L3_1_i;
{
int L2_2_i;
int L2_3_ii;
int L2_4_ip;
int L2_5_j;
flt L2_6_sum;
int L3_7_i;
L2_2_i = 0;
L2_3_ii = 0;
L2_4_ip = 0;
L2_5_j = 0;
L2_6_sum = 0;
{
L3_7_i = 1;
for(;
((1>0)?(L3_7_i<=L1_n):(L3_7_i>=L1_n));
(L3_7_i)+=1 ) {
RTERR_BOUND(L3_7_i<0 || L3_7_i>=(L1_indx)->dim[0]);
L2_4_ip = IDX_PTR(L1_indx,flt)[(L1_indx)->mod[0]*((int)L3_7_i)];
RTERR_BOUND(L2_4_ip<0 || L2_4_ip>=(L1_b)->dim[0]);
L2_6_sum = IDX_PTR(L1_b,flt)[(L1_b)->mod[0]*((int)L2_4_ip)];
RTERR_BOUND(L2_4_ip<0 || L2_4_ip>=(L1_b)->dim[0]);
RTERR_BOUND(L3_7_i<0 || L3_7_i>=(L1_b)->dim[0]);
IDX_PTR(L1_b,flt)[(L1_b)->mod[0]*((int)L2_4_ip)] = IDX_PTR(L1_b,flt)[(L1_b)->mod[0]*((int)L3_7_i)];
 if ((L2_3_ii!=0)) { 
{
real L4_8_j;
int L_Tmp9;
L_Tmp9 = ((L3_7_i)-1);
L4_8_j = L2_3_ii;
for(;
((1>0)?(L4_8_j<=L_Tmp9):(L4_8_j>=L_Tmp9));
(L4_8_j)+=1 ) {
RTERR_BOUND(L3_7_i<0 || L3_7_i>=(L1_a)->dim[0]);
RTERR_BOUND(L4_8_j<0 || L4_8_j>=(L1_a)->dim[1]);
RTERR_BOUND(L4_8_j<0 || L4_8_j>=(L1_b)->dim[0]);
L2_6_sum = (L2_6_sum-(IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L3_7_i)+(L1_a)->mod[1]*((int)L4_8_j)]*IDX_PTR(L1_b,flt)[(L1_b)->mod[0]*((int)L4_8_j)]));
}
}
 } else { 
 if ((L2_6_sum!=0)) { 
L2_3_ii = L3_7_i;
 } 
 } 
RTERR_BOUND(L3_7_i<0 || L3_7_i>=(L1_b)->dim[0]);
IDX_PTR(L1_b,flt)[(L1_b)->mod[0]*((int)L3_7_i)] = L2_6_sum;
}
}
{
L3_1_i = L1_n;
RTERR_RTYPE(!((-1>0)?(L3_1_i<=1):(L3_1_i>=1)));

for(;
((-1>0)?(L3_1_i<=1):(L3_1_i>=1));
(L3_1_i)+=-1 ) {
RTERR_BOUND(L3_1_i<0 || L3_1_i>=(L1_b)->dim[0]);
L2_6_sum = IDX_PTR(L1_b,flt)[(L1_b)->mod[0]*((int)L3_1_i)];
{
real L4_10_j;
L4_10_j = ((L3_1_i)+1);
for(;
((1>0)?(L4_10_j<=L1_n):(L4_10_j>=L1_n));
(L4_10_j)+=1 ) {
RTERR_BOUND(L3_1_i<0 || L3_1_i>=(L1_a)->dim[0]);
RTERR_BOUND(L4_10_j<0 || L4_10_j>=(L1_a)->dim[1]);
RTERR_BOUND(L4_10_j<0 || L4_10_j>=(L1_b)->dim[0]);
L2_6_sum = (L2_6_sum-(IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L3_1_i)+(L1_a)->mod[1]*((int)L4_10_j)]*IDX_PTR(L1_b,flt)[(L1_b)->mod[0]*((int)L4_10_j)]));
}
}
L_Tmp0 = L1_b;
RTERR_BOUND(L3_1_i<0 || L3_1_i>=(L_Tmp0)->dim[0]);
RTERR_BOUND(L3_1_i<0 || L3_1_i>=(L1_a)->dim[0]);
RTERR_BOUND(L3_1_i<0 || L3_1_i>=(L1_a)->dim[1]);
IDX_PTR(L_Tmp0,flt)[(L_Tmp0)->mod[0]*((int)L3_1_i)] = (L2_6_sum/(flt)IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L3_1_i)+(L1_a)->mod[1]*((int)L3_1_i)]);
}
}
}
TRACE_POP("C_lu_back_substitution");
return L_Tmp0;
}
}

/*
 * FUNCTION lu-solve
 */
extern_c struct idx* C_lu_solve(struct idx* L1_a,struct idx* L1_b,struct idx* L1_x)
{
TRACE_PUSH("C_lu_solve");
{
struct idx* L_Tmp0;
{
int L2_1_n;
int L2_2_n1;
Midx_declare(L2_3_0_matrix, 2);
Msrg_declare(L2_4_0_srg);
struct idx* L2_5_a1;
Midx_declare(L2_6_1_matrix, 1);
Msrg_declare(L2_7_1_srg);
struct idx* L2_8_b1;
Midx_declare(L2_9_2_matrix, 1);
Msrg_declare(L2_10_2_srg);
struct idx* L2_11_indx;
int L2_12_i;
int L2_13_j;
Midx_init(L2_3_0_matrix, 2);
Msrg_init(L2_4_0_srg, ST_F);
Midx_init(L2_6_1_matrix, 1);
Msrg_init(L2_7_1_srg, ST_F);
Midx_init(L2_9_2_matrix, 1);
Msrg_init(L2_10_2_srg, ST_F);
L2_1_n = (L1_b)->dim[0];
L2_2_n1 = ((L2_1_n)+1);
(L2_3_0_matrix)->srg = L2_4_0_srg;
Midx_init_dim2(L2_3_0_matrix, L2_2_n1,L2_2_n1);
RTERR_DIM(L2_3_0_matrix->dim[0]<=0);
RTERR_DIM(L2_3_0_matrix->dim[1]<=0);
Midx_maclear(L2_3_0_matrix, flt);
L2_5_a1 = L2_3_0_matrix;
(L2_6_1_matrix)->srg = L2_7_1_srg;
Midx_init_dim1(L2_6_1_matrix, L2_2_n1);
RTERR_DIM(L2_6_1_matrix->dim[0]<=0);
Midx_maclear(L2_6_1_matrix, flt);
L2_8_b1 = L2_6_1_matrix;
(L2_9_2_matrix)->srg = L2_10_2_srg;
Midx_init_dim1(L2_9_2_matrix, L2_2_n1);
RTERR_DIM(L2_9_2_matrix->dim[0]<=0);
Midx_maclear(L2_9_2_matrix, flt);
L2_11_indx = L2_9_2_matrix;
L2_12_i = 0;
L2_13_j = 0;
{
real L3_14_i;
real L_Tmp15;
L3_14_i = 1;
for(;
((1>0)?(L3_14_i<=L2_1_n):(L3_14_i>=L2_1_n));
(L3_14_i)+=1 ) {
RTERR_BOUND(L3_14_i<0 || L3_14_i>=(L2_8_b1)->dim[0]);
L_Tmp15 = ((L3_14_i)-1);
RTERR_BOUND(L_Tmp15<0 || L_Tmp15>=(L1_b)->dim[0]);
IDX_PTR(L2_8_b1,flt)[(L2_8_b1)->mod[0]*((int)L3_14_i)] = IDX_PTR(L1_b,flt)[(L1_b)->mod[0]*((int)L_Tmp15)];
{
real L4_16_j;
real L_Tmp17;
real L_Tmp18;
L4_16_j = 1;
for(;
((1>0)?(L4_16_j<=L2_1_n):(L4_16_j>=L2_1_n));
(L4_16_j)+=1 ) {
RTERR_BOUND(L3_14_i<0 || L3_14_i>=(L2_5_a1)->dim[0]);
RTERR_BOUND(L4_16_j<0 || L4_16_j>=(L2_5_a1)->dim[1]);
L_Tmp17 = ((L3_14_i)-1);
L_Tmp18 = ((L4_16_j)-1);
RTERR_BOUND(L_Tmp17<0 || L_Tmp17>=(L1_a)->dim[0]);
RTERR_BOUND(L_Tmp18<0 || L_Tmp18>=(L1_a)->dim[1]);
IDX_PTR(L2_5_a1,flt)[(L2_5_a1)->mod[0]*((int)L3_14_i)+(L2_5_a1)->mod[1]*((int)L4_16_j)] = IDX_PTR(L1_a,flt)[(L1_a)->mod[0]*((int)L_Tmp17)+(L1_a)->mod[1]*((int)L_Tmp18)];
}
}
}
}
C_lu_decomposition(L2_5_a1, L2_1_n, L2_11_indx);
C_lu_back_substitution(L2_5_a1, L2_1_n, L2_11_indx, L2_8_b1);
{
real L3_19_i;
real L_Tmp20;
L3_19_i = 1;
RTERR_RTYPE(!((1>0)?(L3_19_i<=L2_1_n):(L3_19_i>=L2_1_n)));

for(;
((1>0)?(L3_19_i<=L2_1_n):(L3_19_i>=L2_1_n));
(L3_19_i)+=1 ) {
L_Tmp0 = L1_x;
L_Tmp20 = ((L3_19_i)-1);
RTERR_BOUND(L_Tmp20<0 || L_Tmp20>=(L_Tmp0)->dim[0]);
RTERR_BOUND(L3_19_i<0 || L3_19_i>=(L2_8_b1)->dim[0]);
IDX_PTR(L_Tmp0,flt)[(L_Tmp0)->mod[0]*((int)L_Tmp20)] = IDX_PTR(L2_8_b1,flt)[(L2_8_b1)->mod[0]*((int)L3_19_i)];
}
}
Msrg_free(L2_4_0_srg);
Msrg_free(L2_7_1_srg);
Msrg_free(L2_10_2_srg);
}
TRACE_POP("C_lu_solve");
return L_Tmp0;
}
}

/*
 * FUNCTION int-delta
 */
extern_c real C_int_delta(int L1_x,int L1_y)
{
TRACE_PUSH("C_int_delta");
{
real L_Tmp0;
 if ((L1_x==L1_y)) { 
L_Tmp0 = 1;
 } else { 
L_Tmp0 = 0;
 } 
TRACE_POP("C_int_delta");
return L_Tmp0;
}
}

/*
 * FUNCTION log2
 */
extern_c flt C_log2(flt L1_x)
{
TRACE_PUSH("C_log2");
{
flt L_Tmp0;
L_Tmp0 = (Flog(L1_x)/(flt)Dlog(2));
TRACE_POP("C_log2");
return L_Tmp0;
}
}

/*
 * FUNCTION safe-add--log2
 */
extern_c real C_safe_add__log2(flt L1_sum,flt L1_x)
{
TRACE_PUSH("C_safe_add__log2");
{
real L_Tmp0;
char L_Tmp1;
flt L_Tmp2;
 if ((L1_sum==-1)) { 
L_Tmp1 = 1;
 } else { 
 if ((L1_x==0)) { 
L_Tmp1 = 1;
 } else { 
L_Tmp1 = 0;
 } 
 } 
 if (L_Tmp1) { 
L_Tmp0 = -1;
 } else { 
L_Tmp2 = (flt) C_log2(L1_x);
L_Tmp0 = (L1_sum-L_Tmp2);
 } 
TRACE_POP("C_safe_add__log2");
return L_Tmp0;
}
}

/*
 * FUNCTION safe->--log
 */
extern_c char C_safe_Lt__log(flt L1_x,flt L1_y)
{
TRACE_PUSH("C_safe_Lt__log");
{
char L_Tmp0;
char L_Tmp1;
 if ((L1_y!=-1)) { 
 if ((L1_x==-1)) { 
L_Tmp1 = 1;
 } else { 
 if ((L1_x>L1_y)) { 
L_Tmp1 = 1;
 } else { 
L_Tmp1 = 0;
 } 
 } 
 if (L_Tmp1) { 
L_Tmp0 = 1;
 } else { 
L_Tmp0 = 0;
 } 
 } else { 
L_Tmp0 = 0;
 } 
TRACE_POP("C_safe_Lt__log");
return L_Tmp0;
}
}

/*
 * FUNCTION calculate-entropy
 */
extern_c flt C_calculate_entropy(struct idx* L1_p)
{
TRACE_PUSH("C_calculate_entropy");
{
flt L_Tmp0;
{
flt L2_1_p_i;
flt L2_2_result;
L2_1_p_i = 0;
L2_2_result = 0;
{
real L3_3_i;
int L_Tmp4;
flt L_Tmp5;
L_Tmp4 = (((L1_p)->dim[0])-1);
L3_3_i = 0;
for(;
((1>0)?(L3_3_i<=L_Tmp4):(L3_3_i>=L_Tmp4));
(L3_3_i)+=1 ) {
RTERR_BOUND(L3_3_i<0 || L3_3_i>=(L1_p)->dim[0]);
L2_1_p_i = IDX_PTR(L1_p,flt)[(L1_p)->mod[0]*((int)L3_3_i)];
 if ((L2_1_p_i!=0)) { 
L_Tmp5 = (flt) C_log2(L2_1_p_i);
L2_2_result = (L2_2_result-(L2_1_p_i*L_Tmp5));
 } 
}
}
L_Tmp0 = L2_2_result;
}
TRACE_POP("C_calculate_entropy");
return L_Tmp0;
}
}

/*
 * FUNCTION int-code-length
 */
extern_c real C_int_code_length(flt L1_n)
{
TRACE_PUSH("C_int_code_length");
{
real L_Tmp0;
 if ((L1_n<0)) { 
L_Tmp0 = 0;
 } else { 
L1_n = (L1_n+1);
{
flt L2_1_result;
L2_1_result = (flt) C_log2(2.865);
/* While loop */
goto L_1;
L_0:
{
L1_n = (flt) C_log2(L1_n);
L2_1_result = (L2_1_result+L1_n);
}
/* While loop test*/
L_1:
{
if ((L1_n>1)) goto L_0;

}
L_Tmp0 = L2_1_result;
}
 } 
TRACE_POP("C_int_code_length");
return L_Tmp0;
}
}

/*
 * FUNCTION comb-code-length
 */
extern_c real C_comb_code_length(flt L1_sum,int L1_m)
{
TRACE_PUSH("C_comb_code_length");
{
real L_Tmp0;
char L_Tmp1;
 if ((L1_sum<0)) { 
L_Tmp1 = 1;
 } else { 
 if ((L1_m<=1)) { 
L_Tmp1 = 1;
 } else { 
L_Tmp1 = 0;
 } 
 } 
 if (L_Tmp1) { 
L_Tmp0 = 0;
 } else { 
{
flt L2_2_result;
L2_2_result = (flt) C_log2((L1_sum+L1_m));
{
flt L3_3_i;
int L_Tmp4;
flt L_Tmp5;
flt L_Tmp6;
L_Tmp4 = ((L1_m)-1);
L3_3_i = 1;
for(;
((1>0)?(L3_3_i<=L_Tmp4):(L3_3_i>=L_Tmp4));
(L3_3_i)+=1 ) {
L_Tmp5 = (flt) C_log2((L1_sum+L3_3_i));
L2_2_result = (L2_2_result+L_Tmp5);
L_Tmp6 = (flt) C_log2(L3_3_i);
L2_2_result = (L2_2_result-L_Tmp6);
}
}
L_Tmp0 = L2_2_result;
}
 } 
TRACE_POP("C_comb_code_length");
return L_Tmp0;
}
}

/*
 * FUNCTION rand-p-vector
 */
extern_c char C_rand_p_vector(struct idx* L1_m,flt L1_noise_width)
{
TRACE_PUSH("C_rand_p_vector");
{
{
int L2_0_m_size;
L2_0_m_size = (L1_m)->dim[0];
{
real L3_1_i_elt;
int L_Tmp2;
flt L_Tmp3_rand;
L_Tmp2 = ((L2_0_m_size)-1);
L3_1_i_elt = 0;
for(;
((1>0)?(L3_1_i_elt<=L_Tmp2):(L3_1_i_elt>=L_Tmp2));
(L3_1_i_elt)+=1 ) {
RTERR_BOUND(L3_1_i_elt<0 || L3_1_i_elt>=(L1_m)->dim[0]);
L_Tmp3_rand = (((-1) - (1)) * Frand() + (1));
IDX_PTR(L1_m,flt)[(L1_m)->mod[0]*((int)L3_1_i_elt)] = (1+(L1_noise_width*L_Tmp3_rand));
}
}
{
Midx_declare0(L3_4_0_matrix);
Msrg_declare(L3_5_0_srg);
struct idx* L3_6_m_sum;
Midx_declare0(L3_7_1_matrix);
Msrg_declare(L3_8_1_srg);
struct idx* L_Tmp9;
(L3_4_0_matrix)->ndim = 0;
Msrg_init(L3_5_0_srg, ST_F);
(L3_7_1_matrix)->ndim = 0;
Msrg_init(L3_8_1_srg, ST_F);
(L3_4_0_matrix)->srg = L3_5_0_srg;
Midx_init_dim0(L3_4_0_matrix);
check_main_m0out(L1_m,L3_4_0_matrix);
Midx_m1sum(L1_m,L3_4_0_matrix,flt,flt);
L3_6_m_sum = L3_4_0_matrix;
(L3_7_1_matrix)->srg = L3_8_1_srg;
Midx_init_dim0(L3_7_1_matrix);
Midx_maclear(L3_7_1_matrix, flt);
L_Tmp9 = L3_7_1_matrix;
*IDX_PTR(L_Tmp9,flt) = (1/(flt) *IDX_PTR(L3_6_m_sum,flt));
check_main_m0in_maout(L1_m,L_Tmp9,L1_m);
Midx_m1dotm0(L1_m,L_Tmp9,L1_m,flt,flt,flt);
Msrg_free(L3_5_0_srg);
Msrg_free(L3_8_1_srg);
}
}
TRACE_POP("C_rand_p_vector");
return 0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB safe-/
 */
DH(X_safe_Over)
{
dharg ret;
ret.dh_real =  C_safe_Over(a[1].dh_flt, a[2].dh_flt);
return ret;
}

/*
 * DHDOC safe-/
 */
DHDOC(K_safe_Over_Rf5034de8,X_safe_Over,"C_safe_Over",0,0) = {
DH_FUNC(2),
DH_FLT,
DH_FLT,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB round
 */
DH(X_round)
{
dharg ret;
ret.dh_int =  C_round(a[1].dh_flt);
return ret;
}

/*
 * DHDOC round
 */
DHDOC(K_round_R48e96478,X_round,"C_round",0,0) = {
DH_FUNC(1),
DH_FLT,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB round-using
 */
DH(X_round_using)
{
dharg ret;
ret.dh_flt =  C_round_using(a[1].dh_flt, a[2].dh_flt);
return ret;
}

/*
 * DHDOC round-using
 */
DHDOC(K_round_using_Rdf8b4b24,X_round_using,"C_round_using",0,0) = {
DH_FUNC(2),
DH_FLT,
DH_FLT,
DH_RETURN,
DH_FLT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB round-to
 */
DH(X_round_to)
{
dharg ret;
ret.dh_flt =  C_round_to(a[1].dh_flt, a[2].dh_flt);
return ret;
}

/*
 * DHDOC round-to
 */
DHDOC(K_round_to_Rdf8b4b24,X_round_to,"C_round_to",0,0) = {
DH_FUNC(2),
DH_FLT,
DH_FLT,
DH_RETURN,
DH_FLT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB match-sign
 */
DH(X_match_sign)
{
dharg ret;
ret.dh_real =  C_match_sign(a[1].dh_flt, a[2].dh_flt);
return ret;
}

/*
 * DHDOC match-sign
 */
DHDOC(K_match_sign_Rf5034de8,X_match_sign,"C_match_sign",0,0) = {
DH_FUNC(2),
DH_FLT,
DH_FLT,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB lu-decomposition
 */
DH(X_lu_decomposition)
{
dharg ret;
ret.dh_flt =  C_lu_decomposition(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC lu-decomposition
 */
DHDOC(K_lu_decomposition_R8e6ca1a1,X_lu_decomposition,"C_lu_decomposition",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_WRITE),
DH_FLT,
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_WRITE),
DH_FLT,
DH_RETURN,
DH_FLT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB lu-back-substitution
 */
DH(X_lu_back_substitution)
{
dharg ret;
ret.dh_idx_ptr =  C_lu_back_substitution(a[1].dh_idx_ptr, a[2].dh_int, a[3].dh_idx_ptr, a[4].dh_idx_ptr);
return ret;
}

/*
 * DHDOC lu-back-substitution
 */
DHDOC(K_lu_back_substitution_Rc5a81d1a,X_lu_back_substitution,"C_lu_back_substitution",0,0) = {
DH_FUNC(4),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLT,
DH_INT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_WRITE),
DH_FLT,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_WRITE),
DH_FLT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB lu-solve
 */
DH(X_lu_solve)
{
dharg ret;
ret.dh_idx_ptr =  C_lu_solve(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC lu-solve
 */
DHDOC(K_lu_solve_R07e56038,X_lu_solve,"C_lu_solve",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_WRITE),
DH_FLT,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_WRITE),
DH_FLT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB int-delta
 */
DH(X_int_delta)
{
dharg ret;
ret.dh_real =  C_int_delta(a[1].dh_int, a[2].dh_int);
return ret;
}

/*
 * DHDOC int-delta
 */
DHDOC(K_int_delta_Rcb832de8,X_int_delta,"C_int_delta",0,0) = {
DH_FUNC(2),
DH_INT,
DH_INT,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB log2
 */
DH(X_log2)
{
dharg ret;
ret.dh_flt =  C_log2(a[1].dh_flt);
return ret;
}

/*
 * DHDOC log2
 */
DHDOC(K_log2_R4a596078,X_log2,"C_log2",0,0) = {
DH_FUNC(1),
DH_FLT,
DH_RETURN,
DH_FLT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB safe-add--log2
 */
DH(X_safe_add__log2)
{
dharg ret;
ret.dh_real =  C_safe_add__log2(a[1].dh_flt, a[2].dh_flt);
return ret;
}

/*
 * DHDOC safe-add--log2
 */
DHDOC(K_safe_add__log2_Rf5034de8,X_safe_add__log2,"C_safe_add__log2",0,0) = {
DH_FUNC(2),
DH_FLT,
DH_FLT,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB safe->--log
 */
DH(X_safe_Lt__log)
{
dharg ret;
ret.dh_char =  C_safe_Lt__log(a[1].dh_flt, a[2].dh_flt);
return ret;
}

/*
 * DHDOC safe->--log
 */
DHDOC(K_safe_Lt__log_R778b69c5,X_safe_Lt__log,"C_safe_Lt__log",0,0) = {
DH_FUNC(2),
DH_FLT,
DH_FLT,
DH_RETURN,
DH_BOOL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB calculate-entropy
 */
DH(X_calculate_entropy)
{
dharg ret;
ret.dh_flt =  C_calculate_entropy(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC calculate-entropy
 */
DHDOC(K_calculate_entropy_R5a19ac74,X_calculate_entropy,"C_calculate_entropy",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLT,
DH_RETURN,
DH_FLT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB int-code-length
 */
DH(X_int_code_length)
{
dharg ret;
ret.dh_real =  C_int_code_length(a[1].dh_flt);
return ret;
}

/*
 * DHDOC int-code-length
 */
DHDOC(K_int_code_length_R60d166b4,X_int_code_length,"C_int_code_length",0,0) = {
DH_FUNC(1),
DH_FLT,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB comb-code-length
 */
DH(X_comb_code_length)
{
dharg ret;
ret.dh_real =  C_comb_code_length(a[1].dh_flt, a[2].dh_int);
return ret;
}

/*
 * DHDOC comb-code-length
 */
DHDOC(K_comb_code_length_Re0836de8,X_comb_code_length,"C_comb_code_length",0,0) = {
DH_FUNC(2),
DH_FLT,
DH_INT,
DH_RETURN,
DH_REAL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB rand-p-vector
 */
DH(X_rand_p_vector)
{
dharg ret;
ret.dh_char =  C_rand_p_vector(a[1].dh_idx_ptr, a[2].dh_flt);
return ret;
}

/*
 * DHDOC rand-p-vector
 */
DHDOC(K_rand_p_vector_R570af1dd,X_rand_p_vector,"C_rand_p_vector",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_WRITE,1),
DH_SRG(DHT_WRITE),
DH_FLT,
DH_FLT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_util(void)
{
 dh_define("safe-/", &K_safe_Over_Rf5034de8); 
 dh_define("round", &K_round_R48e96478); 
 dh_define("round-using", &K_round_using_Rdf8b4b24); 
 dh_define("round-to", &K_round_to_Rdf8b4b24); 
 dh_define("match-sign", &K_match_sign_Rf5034de8); 
 dh_define("lu-decomposition", &K_lu_decomposition_R8e6ca1a1); 
 dh_define("lu-back-substitution", &K_lu_back_substitution_Rc5a81d1a); 
 dh_define("lu-solve", &K_lu_solve_R07e56038); 
 dh_define("int-delta", &K_int_delta_Rcb832de8); 
 dh_define("log2", &K_log2_R4a596078); 
 dh_define("safe-add--log2", &K_safe_add__log2_Rf5034de8); 
 dh_define("safe->--log", &K_safe_Lt__log_R778b69c5); 
 dh_define("calculate-entropy", &K_calculate_entropy_R5a19ac74); 
 dh_define("int-code-length", &K_int_code_length_R60d166b4); 
 dh_define("comb-code-length", &K_comb_code_length_Re0836de8); 
 dh_define("rand-p-vector", &K_rand_p_vector_R570af1dd); 
}

int majver_util = 40;
int minver_util = 10;


#endif

