#!/bin/bash
exec lush "$0" "$@"
!#

; Load HMM library
(libload "../Code/load-hmm")

; Initialize GUI framework
;(ogre)

(let ((model-path (nth 1 argv))
      (data-set-path (nth 2 argv))
      (model-counter (nth 3 argv))
      (model-starting-size (nth 4 argv)))
    (defvar dset (new dsource-seq data-set-path))
    (defvar model
      (new hmm model-path data-set-path (val model-starting-size)
	   (val model-counter))))



; Create the top-level trainer.
(defvar trainer (new hmm-trainer model dset ()))  ; <-- Third argument indicates the hmm
                                                  ;       is not new.


(repeat (val (nth 5 argv))
  (==> trainer suggest-move)
  (==> trainer keep-model))




